### ISSUE TITLE
improve detection of VM technology using Ansible Facts

### ISSUE THREAD

**Issue by DasFaultier** [robpomeroy/BrightOS#14]
This will look something like:

```yaml
- import_tasks: "tasks.yml"
  when:    # implicit AND when passing a list
    - ansible_facts.virtualization_role == "guest"
    - ansible_facts.virtualization_type == "VMware"
```

By using facts that are gathered anyway, we can save two tasks and avoid calling the `ansible.builtin.shell` module altogether in this context.
